# Generated by Django 6.0 on 2026-01-23 21:49

import apps.orders.models
from django.db import migrations, models
from django.utils.crypto import get_random_string


def populate_tracking_codes(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    existing = set(
        Order.objects.exclude(tracking_code__isnull=True)
        .exclude(tracking_code='')
        .values_list('tracking_code', flat=True)
    )

    def new_code():
        code = get_random_string(10).upper()
        while code in existing:
            code = get_random_string(10).upper()
        existing.add(code)
        return code

    for order in Order.objects.all():
        if not order.tracking_code or order.tracking_code in existing:
            order.tracking_code = new_code()
            order.save(update_fields=['tracking_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(default='', max_length=20, null=True, blank=True, unique=False),
        ),
        migrations.RunPython(populate_tracking_codes, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('preparing', 'Preparando'), ('in_transit', 'En tránsito'), ('delivered', 'Llegó a destino'), ('completed', 'Finalizado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(default=apps.orders.models.generate_tracking_code, max_length=20, unique=True),
        ),
    ]
