// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 16/5/2026, 10:05:17 p.m.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/marco/OneDrive/Escritorio/WEBPYME/pymeweb-frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/marco/OneDrive/Escritorio/WEBPYME/pymeweb-frontend/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/marco/OneDrive/Escritorio/WEBPYME/pymeweb-frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/marco/OneDrive/Escritorio/WEBPYME/pymeweb-frontend/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/marco/OneDrive/Escritorio/WEBPYME/pymeweb-frontend/app/plugins/**/*.{js,ts,mjs}","C:/Users/marco/OneDrive/Escritorio/WEBPYME/pymeweb-frontend/app/stores/**/*.{js,ts,mjs}","C:/Users/marco/OneDrive/Escritorio/WEBPYME/pymeweb-frontend/app/composables/**/*.{js,ts,mjs}","C:/Users/marco/OneDrive/Escritorio/WEBPYME/pymeweb-frontend/app/utils/**/*.{js,ts,mjs}","C:/Users/marco/OneDrive/Escritorio/WEBPYME/pymeweb-frontend/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/marco/OneDrive/Escritorio/WEBPYME/pymeweb-frontend/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/marco/OneDrive/Escritorio/WEBPYME/pymeweb-frontend/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/marco/OneDrive/Escritorio/WEBPYME/pymeweb-frontend/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;