# Generated by Django 6.0 on 2025-12-17 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_productvariant'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_available', models.IntegerField(default=0)),
                ('stock_minimum', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stores.store')),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalogo.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('ENTRY', 'Entrada'), ('EXIT', 'Salida'), ('ADJUST', 'Ajuste')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='stores.store')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='catalogo.productvariant')),
            ],
        ),
    ]
