# Generated by Django 6.0 on 2026-01-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_product_offer_and_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_marketplace',
            field=models.BooleanField(default=False),
        ),
    ]
