# Generated by Django 6.0 on 2026-01-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
    ]
