# Generated by Django 6.0 on 2026-01-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_contact_email_store_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
