# Generated by Django 6.0.3 on 2026-04-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_store_is_marketplace_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='delivery_fee_mode',
            field=models.CharField(choices=[('at_checkout', 'Cobrar en checkout'), ('at_dispatch', 'Cobrar al despacho')], default='at_dispatch', help_text='Cuándo se cobra el envío', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='extra_drink_price',
            field=models.DecimalField(decimal_places=0, default=1000, help_text='Precio en CLP para bebidas', max_digits=8),
        ),
        migrations.AddField(
            model_name='store',
            name='extra_fries_large_price',
            field=models.DecimalField(decimal_places=0, default=1400, help_text='Precio en CLP para papas grandes', max_digits=8),
        ),
        migrations.AddField(
            model_name='store',
            name='extra_fries_medium_price',
            field=models.DecimalField(decimal_places=0, default=900, help_text='Precio en CLP para papas medianas', max_digits=8),
        ),
        migrations.AddField(
            model_name='store',
            name='extra_sauce_price',
            field=models.DecimalField(decimal_places=0, default=250, help_text='Precio en CLP por unidad de salsa', max_digits=8),
        ),
        migrations.AddField(
            model_name='store',
            name='extra_size_large_price',
            field=models.DecimalField(decimal_places=0, default=1200, help_text='Precio en CLP para tamaño grande', max_digits=8),
        ),
        migrations.AddField(
            model_name='store',
            name='pickup_instructions',
            field=models.TextField(blank=True, help_text='Instrucciones para retiro en local'),
        ),
        migrations.AddField(
            model_name='store',
            name='pickup_skip_queue_enabled',
            field=models.BooleanField(default=True, help_text='¿Permite retiro sin espera?'),
        ),
        migrations.AddField(
            model_name='store',
            name='shipping_base_fee',
            field=models.DecimalField(blank=True, decimal_places=0, default=2000, help_text='Tarifa base de envío en CLP', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='shipping_free_over',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Envío gratis desde este monto en CLP', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='shipping_per_item_fee',
            field=models.DecimalField(blank=True, decimal_places=0, default=200, help_text='Tarifa por item adicional en CLP', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='social_facebook',
            field=models.URLField(blank=True, help_text='URL de Facebook'),
        ),
        migrations.AddField(
            model_name='store',
            name='social_instagram',
            field=models.URLField(blank=True, help_text='URL de Instagram'),
        ),
        migrations.AddField(
            model_name='store',
            name='social_tiktok',
            field=models.URLField(blank=True, help_text='URL de TikTok'),
        ),
        migrations.AddField(
            model_name='store',
            name='social_youtube',
            field=models.URLField(blank=True, help_text='URL de YouTube'),
        ),
    ]
