# Generated by Django 6.0 on 2025-12-17 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('HERO', 'Hero principal'), ('CATEGORIES', 'Categorías destacadas'), ('FEATURED_PRODUCTS', 'Productos destacados'), ('ABOUT_SNIPPET', 'Resumen Nosotros'), ('FACILITIES_SNIPPET', 'Resumen Instalaciones'), ('FAQ_SNIPPET', 'Preguntas frecuentes'), ('CONTACT_SNIPPET', 'Contacto')], max_length=40)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_sections', to='stores.store')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('store', 'section_type')},
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('HOME', 'Home'), ('ABOUT', 'Nosotros'), ('FACILITIES', 'Instalaciones')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('content', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='stores.store')),
            ],
            options={
                'unique_together': {('store', 'page_type')},
            },
        ),
    ]
